export const stores = [
  {
    id: '1',
    name: 'Tech World',
    location: 'New York, USA',
    contact: 'techworld@example.com',
    image: 'https://via.placeholder.com/150/FF0000/FFFFFF?text=Tech+World',
    type: 'Electronics',
  },
  {
    id: '2',
    name: 'Gadget Hub',
    location: 'San Francisco, USA',
    contact: 'gadgethub@example.com',
    image: 'https://via.placeholder.com/150/00FF00/FFFFFF?text=Gadget+Hub',
    type: 'Gadgets',
  },
  {
    id: '3',
    name: 'Electro Mart',
    location: 'Los Angeles, USA',
    contact: 'electromart@example.com',
    image: 'https://via.placeholder.com/150/0000FF/FFFFFF?text=Electro+Mart',
    type: 'Home Appliances',
  },
  {
    id: '4',
    name: 'Device Depot',
    location: 'Chicago, USA',
    contact: 'devicedepot@example.com',
    image: 'https://via.placeholder.com/150/FFFF00/FFFFFF?text=Device+Depot',
    type: 'Mobile Devices',
  },
  {
    id: '5',
    name: 'Gizmo Store',
    location: 'Houston, USA',
    contact: 'gizmstore@example.com',
    image: 'https://via.placeholder.com/150/FF00FF/FFFFFF?text=Gizmo+Store',
    type: 'Gadgets',
  },
  {
    id: '6',
    name: 'Techie Town',
    location: 'Phoenix, USA',
    contact: 'techietown@example.com',
    image: 'https://via.placeholder.com/150/00FFFF/FFFFFF?text=Techie+Town',
    type: 'Electronics',
  },
  {
    id: '7',
    name: 'Gadget Galaxy',
    location: 'Philadelphia, USA',
    contact: 'gadgetgalaxy@example.com',
    image: 'https://via.placeholder.com/150/FF8000/FFFFFF?text=Gadget+Galaxy',
    type: 'Gadgets',
  },
  {
    id: '8',
    name: 'Device World',
    location: 'San Antonio, USA',
    contact: 'deviceworld@example.com',
    image: 'https://via.placeholder.com/150/008000/FFFFFF?text=Device+World',
    type: 'Mobile Devices',
  },
];
